name: Deploy to Gigalixir

on:
  workflow_dispatch: {}

jobs:
  test-and-deploy:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Gigalixir
        if: success()
        run: |
          git remote add gigalixir https://${{ secrets.GIGALIXIR_EMAIL }}:${{ secrets.GIGALIXIR_API_KEY }}@git.gigalixir.com/${{ secrets.GIGALIXIR_APP_NAME }}.git
          git push -f gigalixir HEAD:refs/heads/main
