name: Deploy to DreamHost via sshpass

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Build the Astro site
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Add SSH Key to known_hosts
        env:
          KNOWN_HOSTS_ENTRY: ${{ secrets.KNOWN_HOSTS_ENTRY }}
          HOST: ${{ secrets.HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$KNOWN_HOSTS_ENTRY" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy via rsync and sshpass
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ secrets.HOST }}
          DEPLOY_PATH: zanderlewis.dev/
        run: |
          sshpass -p "$PASSWORD" rsync -avz --delete ./dist/ $USERNAME@$HOST:$DEPLOY_PATH